#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🚀 Running pre-push checks..."

# Run all checks
echo "✨ Running full codebase checks..."
pnpm check || exit 1

# Try building
echo "🏗️  Checking if build succeeds..."
pnpm build || exit 1